[project]
name = "smart-store-adam"
version = "0.1.0"
description = "Business Intelligence Python project for Smart Store"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
]